### ISSUE TITLE
set_high_water_mark() purges files but doesn't update database

### ISSUE THREAD

**Issue by dcf21** [camsci/meteor-pi#35] opened 2015-06-10 01:53 UTC
You'll notice that I've put a try / except clause around line 684 of meteorpi_fdb (where files get os.removed). I think this is a sensible long-term addition, because if for any reason the file system misbehaves and some files go astray (full storage device?), set_high_water_mark() ought to sort the mess out rather than giving you a traceback and landing you with an unusable database.

Currently this is happening rather often.

If I take the test database I've sent you a copy of, and I call update_camera_status() with a valid_from time in the past, it correctly calls set_high_water_mark() and purges the files. However the file and event objects are still in the database:

SQL> SELECT COUNT(*) FROM t_file;

```
   COUNT 
```
# 

```
    2577 
```

SQL> SELECT COUNT(*) FROM t_event;

```
   COUNT 
```
# 

```
      74 
```

Hence, next time I call set_high_water_mark(), I get this warning 2651 times:

Warning: could not remove file </home/dcf21/camsci/meteor-pi/src/cameraControl/../../datadir/firebird_files/38e7b372d0a544bf9e0d1853f50373f5>.

**Comment by dcf21** [comment] 2015-06-10 02:08
... though it seems to be an intermittent fault I can't now replicate ...

**Comment by tomoinn** [comment] 2015-06-10 08:16
Deleting the FileRecord and Event objects should happen from a cascaded delete on t_cameraStatus, as all entries in t_file and t_event have a foreign key relationship to a row in t_cameraStatus set to cascade delete. If that's not happening there's something odd going on, the more interesting query where this manifests is what's in t_cameraStatus, because if there are entries there which shouldn't be there that explains the problem.

Actually, now I think about it, there's a bug here...

**Comment by tomoinn** [comment] 2015-06-10 08:22
...the bug is as follows:

If we have a camera statii valid from t1->t2 and t2->null, and we set the high water mark to t3 where t2>t3>t1, we will correctly delete the second of these status blocks. This will cascade and delete any files with time > t2. However, it will not delete the first block, so files which have times between t3 and t2, which are therefore beyond the high water mark, will not be deleted. The same goes for events. The bug is my not thinking about these cases, and assuming the cascade delete would cover them.

You should be able to reproducibly trigger the bug by creating a status (times in brackets) s1(0-5), s2(5-10), along with some files f1(4),fs2(6), f3(7). If time is set to 3, s2 will be deleted, this will cascade and delete f2,f3 but will leave f1. However, the file on disk will be deleted as the deletion is done in a query based on t_file. Next time the high water mark is pulled back the entry in t_file will still be there but the file on disk won't, leading to the exception.

**Comment by tomoinn** [comment] 2015-06-10 08:23
Fix is to explicitly delete entries in t_file when deleting the files and to stop trying to be clever with cascaded foreign keys (these are still useful but not sufficient)

**Comment by tomoinn** [comment] 2015-06-10 08:52
Dom, can you check that this is no longer happening?

**Comment by tomoinn** [comment] 2015-06-26 00:27
No input from @dcf21 so closing, I'm pretty sure this is fixed.

**Closed as completed by tomoinn** 2015-06-26 00:27 UTC
Labels: Bug, domain:Middleware
